name: Super-Linter, Deployment, and Cypress CI for Frontend

# Trigger the workflow only on push events to the 'staging2' branch
on:
  push:
    branches:
      - staging3

# Define the jobs
jobs:
  deploy-and-test:
    # Specify the OS to run the tests on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the frontend repository
      - name: Checkout Frontend Code
        uses: actions/checkout@v3

      # Step 2: Run Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Set up Node.js for the React project
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      # Step 4: Install frontend dependencies
      - name: Install Frontend Dependencies
        run: npm install

      # Step 5: Build the React app
      - name: Build Frontend
        run: npm run build

      # Step 6: Deploy to Vercel (staging)
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: false # Staging deployment

      # Step 7: Checkout the Cypress repository
      - name: Checkout Cypress Repository
        uses: actions/checkout@v3
        with:
          repository: <your-org-or-user/cypress-tests-repo> # Replace with Cypress repo name
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: cypress-tests # Clone into 'cypress-tests' directory

      # Step 8: Install Cypress dependencies
      - name: Install Cypress Dependencies
        run: npm install
        working-directory: cypress-tests # Navigate to Cypress repo directory

      # Step 9: Run Cypress Tests
      - name: Run Cypress Tests
        run: npx cypress run
        working-directory: cypress-tests
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }} # Deployed frontend URL
